---
cloud_service_group: Jenkins
cloud_service_type: Build
name: Count by Status
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: data.result
        fields:
          - name: value
            operator: count
