---
cloud_service_group: Jenkins
cloud_service_type: Build
name: Count by Server
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT